language: bash
sudo: false

git:
  depth: false

language: elixir

elixir: '1.8.0'
otp_release: '21.0'

services:
  - postgresql

addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10

before_script:
  - psql -U travis -c "create extension postgis"
  - psql -U travis -c "create database aprsme_test"

env:
  global:
    - PGUSER=travis
    - PGHOST=""
    - PGPORT=5433

