version: '2'

networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7.7-r35'
    environment:
      - RABBITMQ_VHOST=aprs
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-tier
  aprs_slurp:
    depends_on:
      - 'rabbitmq'
    image: 'tcollen/aprs_slurp:latest'
    environment:
      - APRS_USERNAME=APRSME-99
      - APRS_SERVER=204.110.191.245:10152
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=aprs
      - RABBITMQ_HOST=rabbitmq
    networks:
      - app-tier
  postgres:
    image: 'mdillon/postgis:10'
    environment:
      - POSTGRES_DB=aprsme
    volumes:
      - ./postgres/prod_data:/var/lib/postgresql/data
    networks:
      - app-tier
  aprsme:
    image: 'aprsme:latest'
    networks:
      - app-tier
    ports:
      - 4000:80
    environment:
      - RABBITMQ_URL=amqp://user:bitnami@rabbitmq:5672/aprs
      - DATABASE_URL=ecto://postgres:postgres@postgres/aprsme
